name: Fake WorkFlow to Use
on:
  workflow_call:
    inputs:
      msg:
        required: true
        type: string
  
  workflow_dispatch:
  inputs:
    msg:
      required: true
      type: choice
      options:
        - Inner Call

jobs:
  inner_job1:
    name: Inner job 1
    runs-on: ubuntu-20.04

    steps:
      - name: fake job
        run: |
          echo "${{ github.event.inputs.environment }}" 
