name: Caller1
on: 
  workflow_dispatch:
    inputs:
      msg:
        required: true
        type: choice
        options:
          - Caller 1

jobs:
  caller1_job1:
    uses: ./.github/workflows/inner_workflow.yml
    with:
      msg: ${{ github.event.inputs.msg }}